CREATE DATABASE IF NOT EXISTS INCIDENT_TRACKER;
USE INCIDENT_TRACKER;

CREATE TABLE IF NOT EXISTS INCIDENT (
    ID BINARY(16) PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    SERVICE VARCHAR(255) NOT NULL,
    SEVERITY VARCHAR(10),
    STATUS VARCHAR(20),
    OWNER VARCHAR(255),
    SUMMARY TEXT,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP
    );

INSERT INTO incident
(ID,TITLE,SERVICE,SEVERITY,STATUS,owner,SUMMARY,CREATED_AT)
VALUES
    (UUID_TO_BIN(UUID()),'Payment failure 1','PAYMENT','SEV1','OPEN','alice','auto generated',NOW());
